version: '3'

services:
  dev_environment:
    # build .devcontainer/Dockerfile
    build: .
    volumes:
      # Mounts the project folder to '/workspace'. The target path inside the container
      # should match what your application expects. In this case, the compose file is
      # in a sub-folder, so you will mount '..'. You would then reference this path as the
      # 'workspaceFolder' in '.devcontainer/devcontainer.json' so VS Code starts here.
      - ..:/workspace/spdx_lite_depends:cached
    # we need to attach to dev_environment so that command needs to run infinitely.
    command: sleep infinity

  fossology:
    image: fossology/fossology
    ports:
      - "8081:80"
